


taipei_accidents_eng <- taipei_accidents_zh |>
  
  # convert codes to values
  mutate( 
    
    vehicle_type = case_match(車種,
                              "大客車 - 公營公車" ~ "Bus - Public",
                              "大客車 - 民營公車" ~ "Bus - Private",
                              "大客車 - 公營客運" ~ "Bus - Public Transport",
                              "大客車 - 民營客運" ~ "Bus - Private Transport",
                              "大客車 - 遊覽車" ~ "Bus - Tour Bus",
                              "大客車 - 自用大客車" ~ "Bus - Private Use",
                              
                              "大貨車 - 營業用" ~ "Truck - Commercial",
                              "大貨車 - 自用" ~ "Truck - Private Use",
                              
                              "全聯結車 - 營業用" ~ "Articulated Truck - Commercial",
                              "全聯結車 - 自用" ~ "Articulated Truck - Private Use",
                              
                              "半聯結車 - 營業用" ~ "Semi-Trailer Truck - Commercial",
                              "半聯結車 - 自用" ~ "Semi-Trailer Truck - Private Use",
                              
                              "曳引車 - 營業用" ~ "Tractor Truck - Commercial",
                              "曳引車 - 自用" ~ "Tractor Truck - Private Use",
                              
                              "小客車 - 計程車" ~ "Car - Taxi",
                              "小客車 - 租賃車" ~ "Car - Rental",
                              "小客車 - 自用" ~ "Car - Private Use",
                              
                              "小貨車(含客、貨 兩用) - 營業用" ~ "Light Truck (Passenger/Truck) - Commercial",
                              "小貨車(含客、貨 兩用) - 自用" ~ "Light Truck (Passenger/Truck) - Private Use",
                              "小貨車(含客、貨 兩用) - 租賃小貨車" ~ "Light Truck (Passenger/Truck) - Rental",
                              
                              "機車 - 大型重型1(550C.C.以上)" ~ "Motorcycle - Heavy 1 (>550 C.C.)",
                              "機車 - 大型重型2(250-550C.C.)" ~ "Motorcycle - Heavy 2 (250-550 C.C.)",
                              "機車 - 普通重型" ~ "Motorcycle - Standard Heavy",
                              "機車 - 普通輕型" ~ "Motorcycle - Standard Light",
                              "機車 - 小型輕型" ~ "Motorcycle - Small Light",
                              
                              "軍車 - 大客車" ~ "Military Vehicle - Bus",
                              "軍車 - 載重車" ~ "Military Vehicle - Truck",
                              "軍車 - 小型車" ~ "Military Vehicle - Car",
                              
                              "特種車 - 救護車" ~ "Special Vehicle - Ambulance",
                              "特種車 - 消防車" ~ "Special Vehicle - Fire Truck",
                              "特種車 - 警備車" ~ "Special Vehicle - Police Vehicle",
                              "特種車 - 工程車" ~ "Special Vehicle - Engineering Vehicle",
                              "特種車 - 其他特種車" ~ "Special Vehicle - Other Special Vehicle",
                              
                              "慢車 - 腳踏自行車" ~ "Slow Vehicle - Bicycle",
                              "慢車 - 電動輔助自行車" ~ "Slow Vehicle - Electric Assisted Bicycle",
                              "慢車 - 電動自行車/微型電動二輪車" ~ "Slow Vehicle - Electric Bicycle / Micro E-Two-Wheel",
                              "慢車 - 人力車" ~ "Slow Vehicle - Rickshaw",
                              "慢車 - 獸力車" ~ "Slow Vehicle - Animal Drawn Vehicle",
                              "慢車 - 其他慢車" ~ "Slow Vehicle - Other Slow Vehicle",
                              "慢車 - 個人行動運具" ~ "Slow Vehicle - Personal Mobility Device",
                              
                              "其他車 - 拼裝車" ~ "Other Vehicle - Assembled Vehicle",
                              "其他車 - 農耕用車(或機械)" ~ "Other Vehicle - Agricultural Vehicle (or Machinery)",
                              "其他車 - 動力機械" ~ "Other Vehicle - Powered Machinery",
                              "其他車 - 拖車(架)" ~ "Other Vehicle - Trailer",
                              "其他車 - 火車" ~ "Other Vehicle - Train",
                              "其他車 - 其他車" ~ "Other Vehicle - Other Vehicles",
                              
                              "人 - 行人" ~ "Person - Pedestrian",
                              "人 - 乘客" ~ "Person - Passenger",
                              "人 - 其他人" ~ "Person - Other",
                              "人 - 輔助代步器材" ~ "Person - Mobility Aid",
                              .default = 車種),
    
    
    
    sex = case_match(性別,
                     "男" ~ "Male",
                     "女" ~ "Female",
                     "無或物(動物、堆置物)" ~ "None or Object (Animals, Piles of Objects)",
                     "肇事逃逸尚未查獲" ~ "Unresolved Hit and Run",
                     "無人駕駛自動車" ~ "Autonomous Self-Driving Vehicle"),
    
    injury_severity = case_match(受傷程度,
                                 "24小時內死亡" ~ "Death within 24 hours",
                                 "受傷" ~ "Injured",
                                 "未受傷" ~ "Not Injured",
                                 "不明" ~ "Unknown",
                                 "2-30日內死亡" ~ "Death within 2-30 days"),
    
    
    
    weather = case_match(天候,
                         "暴雨" ~ "Heavy Rain",
                         "強風" ~ "Strong Wind",
                         "風沙" ~ "Sandstorm",
                         "霧或煙" ~ "Fog or Smoke",
                         "雪" ~ "Snow",
                         "雨" ~ "Rain",
                         "陰" ~ "Cloudy",
                         "晴" ~ "Sunny",
                         "風" ~ "Wind"),
    
    # Taipei changed their form on July 1st, 2023
    road_type = ifelse(發生日期 > "2023-07-01", 
                       case_match(道路型態,
                                  "三岔路" ~ "Three-way Intersection",
                                  "四岔路" ~ "Four-way Intersection",
                                  "多岔路" ~ "Multiple-way Intersection", 
                                  "隧道" ~ "Tunnel",
                                  "地下道" ~ "Underpass",
                                  "橋樑" ~ "Bridge",
                                  "涵洞" ~ "Culvert",
                                  "高架道路" ~ "Elevated Road",
                                  "彎曲路及附近" ~ "Curved Road and Nearby",
                                  "坡路" ~ "Slope",
                                  "巷弄" ~ "Alley",
                                  "直路" ~ "Straight Road",
                                  "圓環" ~ "Roundabout",
                                  "廣場" ~ "Plaza",
                                  "休息站或服務區" ~ "Rest Area or Service Area",
                                  "輕軌共用道路" ~ "Light Rail Shared Road",
                                  "其他" ~ "Other",
                                  .default = as.character(道路型態)
                       ),
                       
                       case_match(道路型態,
                                    "三岔路" ~ "Three-way Intersection",
                                    "四岔路" ~ "Four-way Intersection",
                                    "多岔路" ~ "Multiple-way Intersection", 
                                    "隧道" ~ "Tunnel",
                                    "地下道" ~ "Underpass",
                                    "橋樑" ~ "Bridge",
                                    "涵洞" ~ "Culvert",
                                    "高架道路" ~ "Elevated Road",
                                    "彎曲路及附近" ~ "Curved Road and Nearby",
                                    "坡路" ~ "Slope",
                                    "巷弄" ~ "Alley",
                                    "直路" ~ "Straight Road",
                                    "其他" ~ "Other",
                                    "圓環" ~ "Roundabout",
                                    "廣場" ~ "Plaza",
                                    .default = as.character(道路型態)
                       )),
                       
                       accident_location = case_match(事故位置, 
                                                      "交岔路口內" ~ "Inside Intersection",
                                                      "交岔口附近" ~ "Near Intersection",
                                                      "機慢車待轉區" ~ "Motorcycle/Slow Vehicle Waiting Area",
                                                      "機慢車停等區" ~ "Motorcycle/Slow Vehicle Stopping Area", 
                                                      "交通島(含槽化線)" ~ "Traffic Island (including channelized lines)",
                                                      "迴轉道" ~ "U-turn Lane",
                                                      "快車道" ~ "Fast Lane",
                                                      "慢車道" ~ "Slow Lane", 
                                                      "一般車道(未劃分快慢車道)" ~ "General Lane (No Speed Segregation)",
                                                      "公車專用道" ~ "Bus-only Lane",
                                                      "機車專用道" ~ "Motorcycle-only Lane",
                                                      "機車優先道" ~ "Motorcycle Priority Lane",
                                                      "路肩、路緣" ~ "Shoulder / Road Edge",
                                                      "加速車道" ~ "Acceleration Lane",
                                                      "減速車道" ~ "Deceleration Lane",
                                                      "直線匝道" ~ "Straight Ramp",
                                                      "環道匝道" ~ "Roundabout Ramp",
                                                      "行人穿越道" ~ "Pedestrian Crossing",
                                                      "行人穿越道附近" ~ "Near Pedestrian Crossing",
                                                      "人行道" ~ "Sidewalk",
                                                      "收費站附近" ~ "Near Toll Booth",
                                                      "其他" ~ "Other",
                                                      "自行車專用道" ~ "Bicycle Lane",
                                                      "人行道標線" ~ "Sidewalk Markings",
                                                      "騎樓" ~ "Arcade / Covered Walkway",
                                                      .default = as.character(道路型態)
                       ),
                       
                       lighting = case_match(光線,
                                             "日間自然光線" ~ "Daylight",
                                             "晨或暮光" ~ "Dawn or Dusk",
                                             "夜間(隧道地下道涵洞)有照明" ~ "Night (Tunnel/Underpass/Culvert) with Lighting",
                                             "夜間(隧道地下道涵洞)無照明" ~ "Night (Tunnel/Underpass/Culvert) without Lighting",
                                             "有照明且開啟" ~ "Lighting On",
                                             "有照明未開啟或障" ~ "Lighting Off or Obstructed",
                                             "無照明" ~ "No Lighting", 
                                             .default = as.character(光線)),
    
    
    
    road_lighting = case_match(道路照明設備,
                               "日間自然光線" ~ "Daylight",
                               "晨或暮光" ~ "Dawn or Dusk",
                               "夜間(隧道地下道涵洞)有照明" ~ "Night (Tunnel/Underpass/Culvert) with Lighting",
                               "夜間(隧道地下道涵洞)無照明" ~ "Night (Tunnel/Underpass/Culvert) without Lighting",
                               "有照明且開啟" ~ "Lighting On",
                               "有照明未開啟或障" ~ "Lighting Off or Obstructed",
                               "無照明" ~ "No Lighting",
                               .default = as.character(道路照明設備)
    ),
    
    road_category = case_match(道路類別,
                               "國道" ~ "National Highway",
                               "省道" ~ "Provincial Highway",
                               "縣道" ~ "County Road",
                               "鄉道" ~ "Township Road",
                               "市區道路" ~ "Urban Road",
                               "村里道路" ~ "Village Road",
                               "專用道路" ~ "Dedicated Road",
                               "其他" ~ "Other",
                               "快速(公)道路" ~ "Expressway / Rapid Road",
                               .default = as.character(道路類別)
    ),
    
    road_surface_material = case_match(路面鋪裝,
                                       "柏油" ~ "Asphalt",
                                       "水泥" ~ "Concrete",
                                       "碎石" ~ "Gravel",
                                       "其他鋪裝" ~ "Other Pavement",
                                       "無鋪裝" ~ "Unpaved"
    ),
    
    road_surface_condition = case_match(路面狀態,
                                        "冰雪" ~ "Icy / Snowy",
                                        "油滑" ~ "Slippery / Oily",
                                        "泥濘" ~ "Muddy",
                                        "濕潤" ~ "Wet",
                                        "乾燥" ~ "Dry"
    ),
    
    
    road_defect = case_match(路面缺陷,
                             "路面鬆軟" ~ "Soft Surface",
                             "突出(高低)不平" ~ "Uneven / Raised or Lowered Surface",
                             "有坑洞" ~ "Potholes",
                             "無缺陷" ~ "No Defect",
                             "隆起或凹陷不平" ~ "Bumps or Depressions"
    ),
    
    road_obstacle_type = case_match(道路障礙_障礙物,
                                    "道路工事(程)中" ~ "Under Road Construction",
                                    "有堆積物" ~ "Debris / Accumulated Objects",
                                    "路上有停車" ~ "Parked Vehicles on Road",
                                    "其他障礙物" ~ "Other Obstacles",
                                    "無障礙物" ~ "No Obstacles",
                                    "攤位、棚架" ~ "Stalls / Canopies"
    ),
    
    road_obstacle_visibility = case_match(道路障礙_視距,
                                          "彎道" ~ "Curve",
                                          "坡道" ~ "Slope",
                                          "建築物" ~ "Buildings",
                                          "樹木、農作物" ~ "Trees / Crops",
                                          "路上停放車輛" ~ "Parked Vehicles on Road",
                                          "其他" ~ "Other",
                                          "良好" ~ "Good Visibility",
                                          "有遮蔽物 - 建築物" ~ "Obstructed - Buildings",
                                          "有遮蔽物 - 樹木、農作物" ~ "Obstructed - Trees / Crops",
                                          "有遮蔽物 - 路上停放車輛" ~ "Obstructed - Parked Vehicles",
                                          "有遮蔽物 - 施工圍籬" ~ "Obstructed - Construction Barriers",
                                          "有遮蔽物 - 其他" ~ "Obstructed - Other",
                                          "無遮蔽物 - 良好" ~ "Unobstructed - Good"
    ),
    
    
    signal_type = case_match(號誌種類,
                             "行車管制號誌" ~ "Traffic Control Signal",
                             "行車管制號誌(附設行人專用號誌)" ~ "Traffic Control Signal with Pedestrian Signal",
                             "閃光號誌" ~ "Flashing Signal",
                             "無號誌" ~ "No Signal"
    ),
    
    signal_operation = case_match(號誌動作,
                                  "正常" ~ "Normal",
                                  "不正常" ~ "Abnormal",
                                  "無動作" ~ "No Operation",
                                  "無號誌" ~ "No Signal"
    ),
    
    lane_division_direction = case_match(車道劃分_分向,
                                         "中央分向島 - 寬式(50 公分以上)" ~ "Central Divider - Wide (≥50 cm)",
                                         "中央分向島 - 窄式附柵欄" ~ "Central Divider - Narrow with Fence",
                                         "中央分向島 - 窄式無柵欄" ~ "Central Divider - Narrow without Fence",
                                         "雙向禁止超車線 - 附標記" ~ "Two-way No-Passing Line with Marking",
                                         "雙向禁止超車線 - 無標記" ~ "Two-way No-Passing Line without Marking",
                                         "單向禁止超車線 - 附標記" ~ "One-way No-Passing Line with Marking",
                                         "單向禁止超車線 - 無標記" ~ "One-way No-Passing Line without Marking",
                                         "行車分向線 - 附標記" ~ "Lane Divider Line with Marking",
                                         "行車分向線 - 無標記" ~ "Lane Divider Line without Marking",
                                         "無分向設施" ~ "No Divider Facility"
    ),
    
    lane_division_fast_or_normal = case_match(車道劃分_快車道或一般車道間,
                                              "禁止變換車道線(附標記)" ~ "Lane Change Prohibited Line (with Marking)",
                                              "禁止變換車道線(無標記)" ~ "Lane Change Prohibited Line (no Marking)",
                                              "車道線(附標記)" ~ "Lane Line (with Marking)",
                                              "車道線(無標記)" ~ "Lane Line (no Marking)",
                                              "未繪設車道線" ~ "No Lane Line Marked"
    ),
    
    
    
    lane_division_fast_slow = case_match(車道劃分_快慢車道間,
                                         "寬式快慢車道分隔島(50 公分以上)" ~ "Wide Fast/Slow Lane Divider (≥50 cm)",
                                         "窄式快慢車道分隔島(附柵欄)" ~ "Narrow Fast/Slow Lane Divider with Fence",
                                         "窄式快慢車道分隔島(無柵欄)" ~ "Narrow Fast/Slow Lane Divider without Fence",
                                         "快慢車道分隔線" ~ "Fast/Slow Lane Divider Line",
                                         "未繪設快慢車道分隔線" ~ "No Fast/Slow Lane Divider Line Marked"
    ),
    
    lane_division_edge_line = case_match(車道劃分_路面邊線,
                                         "有" ~ "Present",
                                         "無" ~ "Absent"
    ),
    
    accident_type_and_pattern = case_match(事故類型及型態, 
                                           "人與車 - 對向通行中" ~ "Pedestrian & Vehicle - Opposite Direction",
                                           "人與車 - 同向通行中" ~ "Pedestrian & Vehicle - Same Direction",
                                           "人與車 - 穿越道路中" ~ "Pedestrian & Vehicle - Crossing Road",
                                           "人與車 - 在路上嬉戲" ~ "Pedestrian & Vehicle - Playing on Road",
                                           "人與車 - 在路上作業中" ~ "Pedestrian & Vehicle - Working on Road",
                                           "人與車 - 衝進路中" ~ "Pedestrian & Vehicle - Running into Road",
                                           "人與車 - 從停車後(或中)穿出" ~ "Pedestrian & Vehicle - Emerging from Parked Vehicle",
                                           "人與車 - 佇立路邊(外)" ~ "Pedestrian & Vehicle - Standing by Roadside",
                                           "人與車 - 其他" ~ "Pedestrian & Vehicle - Other",
                                           "車與車 - 對撞" ~ "Vehicle & Vehicle - Head-on Collision",
                                           "車與車 - 對向擦撞" ~ "Vehicle & Vehicle - Opposite Direction Sideswipe",
                                           "車與車 - 同向擦撞" ~ "Vehicle & Vehicle - Same Direction Sideswipe",
                                           "車與車 - 追撞" ~ "Vehicle & Vehicle - Rear-end Collision",
                                           "車與車 - 倒車撞" ~ "Vehicle & Vehicle - Backing Collision",
                                           "車與車 - 路口交岔撞" ~ "Vehicle & Vehicle - Intersection Collision",
                                           "車與車 - 側撞" ~ "Vehicle & Vehicle - Side Collision",
                                           "車與車 - 其他" ~ "Vehicle & Vehicle - Other",
                                           "車輛本身 - 路上翻車、摔倒" ~ "Single Vehicle - Overturned / Fallen on Road",
                                           "車輛本身 - 衝出路外" ~ "Single Vehicle - Run off Road",
                                           "車輛本身 - 撞護欄(樁)" ~ "Single Vehicle - Hit Guardrail / Bollard",
                                           "車輛本身 - 撞號誌、標誌桿" ~ "Single Vehicle - Hit Traffic Signal / Sign Pole",
                                           "車輛本身 - 撞收費亭" ~ "Single Vehicle - Hit Toll Booth",
                                           "車輛本身 - 撞交通島" ~ "Single Vehicle - Hit Traffic Island",
                                           "車輛本身 - 撞非固定設施" ~ "Single Vehicle - Hit Non-fixed Object",
                                           "車輛本身 - 撞橋梁、建築物" ~ "Single Vehicle - Hit Bridge / Building",
                                           "車輛本身 - 撞路樹、電桿" ~ "Single Vehicle - Hit Roadside Tree / Pole",
                                           "車輛本身 - 撞動物" ~ "Single Vehicle - Hit Animal",
                                           "車輛本身 - 撞工程施工" ~ "Single Vehicle - Hit Construction",
                                           "車輛本身 - 其他" ~ "Single Vehicle - Other",
                                           "車輛本身 - 撞橋樑(橋墩)" ~ "Single Vehicle - Hit Bridge (Pier)",
                                           "車輛本身 - 撞建築物" ~ "Single Vehicle - Hit Building",
                                           "車輛本身 - 撞路樹" ~ "Single Vehicle - Hit Roadside Tree",
                                           "車輛本身 - 撞電桿" ~ "Single Vehicle - Hit Utility Pole",
                                           .default = as.character(道路型態)
    ),
    
    
    
    main_injury_location = case_match(主要傷處,
                                      "頭部" ~ "Head",
                                      "頸部" ~ "Neck",
                                      "胸部" ~ "Chest",
                                      "腹部" ~ "Abdomen", 
                                      "腰部" ~ "Waist",
                                      "背脊部" ~ "Back / Spine",
                                      "手(腕)部" ~ "Hand / Wrist",
                                      "腿(腳)部" ~ "Leg / Foot", 
                                      "多數傷" ~ "Multiple Injuries",
                                      "無" ~ "None",
                                      "不明" ~ "Unknown"
    ),
    
    protective_device = case_match(保護裝置,
                                   "戴安全帽或繫安全帶(使用幼童安全椅)" ~ "Wearing Helmet or Seatbelt (Using Child Seat)",
                                   "未戴安全帽或未繫安全帶(未使用幼童安全椅)" ~ "Not Wearing Helmet or Seatbelt (No Child Seat)",
                                   "不明" ~ "Unknown",
                                   "其他(無需使用保護裝備之人)/(行人、慢車駕駛人)" ~ "Other (No Protective Equipment Needed / Pedestrians or Slow Vehicle Drivers)", 
                                   "戴半罩式安全帽" ~ "Wearing Half-face Helmet",
                                   "戴非半罩式安全帽" ~ "Wearing Non-Half-face Helmet",
                                   "有繫安全帶(使用幼童安全椅)" ~ "Seatbelt Fastened (Using Child Seat)"
    ),
    
    helmet = case_match(安全帽,
                        "戴安全帽或繫安全帶(使用幼童安全椅)" ~ "Wearing Helmet or Seatbelt (Using Child Seat)",
                        "未戴安全帽或未繫安全帶(未使用幼童安全椅)" ~ "Not Wearing Helmet or Seatbelt (No Child Seat)",
                        "不明" ~ "Unknown",
                        "其他(無需使用保護裝備之人)/(行人、慢車駕駛人)" ~ "Other (No Protective Equipment Needed / Pedestrians or Slow Vehicle Drivers)", 
                        "戴半罩式安全帽" ~ "Wearing Half-face Helmet",
                        "戴非半罩式安全帽" ~ "Wearing Non-Half-face Helmet",
                        "有繫安全帶(使用幼童安全椅)" ~ "Seatbelt Fastened (Using Child Seat)"
    ),
    
    
    
    mobile_phone_use = case_match(行動電話,
                                  "未使用" ~ "Not Using",
                                  "使用手持或有礙駕駛安全" ~ "Using Handheld / Impairs Driving Safety",
                                  "使用免持或未有礙駕駛安全" ~ "Using Hands-free / Does Not Impair Driving",
                                  "不明" ~ "Unknown", 
                                  "非汽(機)車駕駛人" ~ "Not Vehicle Driver"
    ),
    
    vehicle_purpose = case_match(車輛用途,
                                 "砂石車" ~ "Sand / Gravel Truck",
                                 "幼童專用車" ~ "Child-specific Vehicle",
                                 "校車" ~ "School Bus",
                                 "身障特製車" ~ "Special Vehicle for Disabled", 
                                 "教練車" ~ "Driving School Vehicle",
                                 "裝載危險物品車" ~ "Vehicle Carrying Hazardous Materials",
                                 "其他" ~ "Other",
                                 "非駕駛人及乘客" ~ "Not Driver or Passenger"
    ),
    
    participant_action_status = case_match(當事者行動狀態, 
                                           "車的狀態 - 起步" ~ "Vehicle Status - Starting",
                                           "車的狀態 - 倒車" ~ "Vehicle Status - Reversing",
                                           "車的狀態 - 停車操作中" ~ "Vehicle Status - Parking in Progress",
                                           "車的狀態 - 超車(含超越)" ~ "Vehicle Status - Overtaking",
                                           "車的狀態 - 左轉彎" ~ "Vehicle Status - Left Turn",
                                           "車的狀態 - 轉彎" ~ "Vehicle Status - Turning",
                                           "車的狀態 - 向左變換車道" ~ "Vehicle Status - Lane Change Left",
                                           "車的狀態 - 向右變換車道" ~ "Vehicle Status - Lane Change Right", 
                                           "車的狀態 - 向前直行中" ~ "Vehicle Status - Moving Forward",
                                           "車的狀態 - 插入行列" ~ "Vehicle Status - Merging into Line",
                                           "車的狀態 - 轉或橫越道路中" ~ "Vehicle Status - Turning or Crossing Road",
                                           "車的狀態 - 減速或急停止" ~ "Vehicle Status - Slowing or Sudden Stop",
                                           "車的狀態 - 靜止(引擎熄火)" ~ "Vehicle Status - Stationary (Engine Off)",
                                           "車的狀態 - 停等(引擎未熄火)" ~ "Vehicle Status - Stopped (Engine On)",
                                           "車的狀態 - 其他" ~ "Vehicle Status - Other",
                                           "人的狀態 - 步行" ~ "Pedestrian Status - Walking",
                                           "人的狀態 - 靜立 (止)" ~ "Pedestrian Status - Standing",
                                           "人的狀態 - 奔跑" ~ "Pedestrian Status - Running",
                                           "人的狀態 - 上、下車" ~ "Pedestrian Status - Boarding / Alighting",
                                           "人的狀態 - 其他" ~ "Pedestrian Status - Other",
                                           "不明" ~ "Unknown"
    ),
    
    
    driver_license_status = case_match(駕駛資格情形,
                                       "有正常駕照" ~ "Valid License",
                                       "無照(未達考照年齡)" ~ "No License (Underage)",
                                       "無照(已達考照年齡)" ~ "No License (Eligible Age)",
                                       "越級駕駛" ~ "Driving Beyond License Class",
                                       "照被吊扣" ~ "License Suspended",
                                       "駕照被吊(註)銷" ~ "License Revoked",
                                       "不明" ~ "Unknown",
                                       "無需駕照之人/非汽(機)車駕駛人" ~ "No License Required / Not a Vehicle Driver"
    ),
    
    driver_license_type = case_match(駕駛執照種類,
                                     "職業駕照 - 聯結車" ~ "Professional License - Articulated Vehicle",
                                     "職業駕照 - 大客車" ~ "Professional License - Large Bus",
                                     "職業駕照 - 大貨車" ~ "Professional License - Large Truck",
                                     "職業駕照 - 小型車" ~ "Professional License - Small Vehicle",
                                     "普通駕照 - 聯結車" ~ "Ordinary License - Articulated Vehicle",
                                     "普通駕照 - 大客車" ~ "Ordinary License - Large Bus",
                                     "普通駕照 - 大貨車" ~ "Ordinary License - Large Truck",
                                     "普通駕照 - 小型車" ~ "Ordinary License - Small Vehicle",
                                     "機車駕照 - 大型重型" ~ "Motorcycle License - Large Heavy",
                                     "機車駕照 - 普通重型" ~ "Motorcycle License - Standard Heavy",
                                     "機車駕照 - 輕型" ~ "Motorcycle License - Light",
                                     "軍用駕照 - 大客車" ~ "Military License - Large Bus",
                                     "軍用駕照 - 載重車" ~ "Military License - Cargo Vehicle",
                                     "軍用駕照 - 小型車" ~ "Military License - Small Vehicle",
                                     "其他 - 國際(外國)駕照" ~ "Other - International (Foreign) License",
                                     "其他 - 其他駕照(證)" ~ "Other - Other License / Certificate",
                                     "其他 - 學習駕駛證" ~ "Other - Learner’s Permit",
                                     "其他 - 無駕駛執照" ~ "Other - No License",
                                     "其他 - 不明" ~ "Other - Unknown",
                                     "其他 - 無需駕照之人/非汽(機)車駕駛人" ~ "Other - No License Required / Not a Vehicle Driver",
                                     "機車駕照 - 小型輕型" ~ "Motorcycle License - Small / Light"
    ),
    
    alcohol_status = case_match(飲酒情形, 
                                "經觀察未飲酒" ~ "Observed Not Drinking",
                                "經檢測無酒精反應" ~ "Tested No Alcohol Response",
                                "呼氣未滿 0.15 mg/L或血液檢測未滿 0.03%" ~ "Breath <0.15 mg/L or Blood <0.03%",
                                "呼氣達0.15以上未滿0.25 mg/L或血液 0.03%以上未滿0.05%" ~ "Breath 0.15-0.25 mg/L or Blood 0.03%-0.05%", 
                                "呼氣達0.25以上未滿0.40 mg/L或血液 0.05%以上未滿0.08%" ~ "Breath 0.25-0.40 mg/L or Blood 0.05%-0.08%",
                                "呼氣達0.4以上未滿0.55mg/L或血液達 0.08%以上未滿0.11%" ~ "Breath 0.40-0.55 mg/L or Blood 0.08%-0.11%",
                                "呼氣達0.55以上未滿0.80 mg/L或血液 0.11%以上未滿0.16%" ~ "Breath 0.55-0.80 mg/L or Blood 0.11%-0.16%",
                                "呼氣檢測 0.80 mg/L以上或血液檢測 0.16%以上" ~ "Breath ≥0.80 mg/L or Blood ≥0.16%", 
                                "駕駛人無法檢測" ~ "Driver Unable to Test",
                                "非駕駛人未檢測" ~ "Not Driver / Not Tested",
                                "駕駛人不明" ~ "Driver Unknown"
    ),
    
    
    
    vehicle_impact_part1 = case_match(車輛撞擊部位1, 
                                      "汽車 - 前車頭" ~ "Car - Front",
                                      "汽車 - 右側車身" ~ "Car - Right Side",
                                      "汽車 - 後車尾" ~ "Car - Rear",
                                      "汽車 - 左側車身" ~ "Car - Left Side", 
                                      "汽車 - 右前車頭(身)" ~ "Car - Front Right",
                                      "汽車 - 右後車尾(身)" ~ "Car - Rear Right",
                                      "汽車 - 左後車尾(身)" ~ "Car - Rear Left",
                                      "汽車 - 左前車頭(身)" ~ "Car - Front Left", 
                                      "汽車 - 車頂" ~ "Car - Roof",
                                      "汽車 - 車底" ~ "Car - Undercarriage",
                                      "機車與自行車 - 前車頭" ~ "Motorbike / Bicycle - Front",
                                      "機車與自行車 - 右側車身" ~ "Motorbike / Bicycle - Right Side",
                                      "機車與自行車 - 後車尾" ~ "Motorbike / Bicycle - Rear", 
                                      "機車與自行車 - 左側車身" ~ "Motorbike / Bicycle - Left Side",
                                      "其他 - 不明" ~ "Other - Unknown",
                                      "其他 - 無撞擊" ~ "Other - No Impact",
                                      "其他 - 非汽、機及自行車" ~ "Other - Not Car, Motorbike, or Bicycle"
    ),
    
    vehicle_impact_part2 = case_match(車輛撞擊部位2, 
                                      "汽車 - 前車頭" ~ "Car - Front",
                                      "汽車 - 右側車身" ~ "Car - Right Side",
                                      "汽車 - 後車尾" ~ "Car - Rear",
                                      "汽車 - 左側車身" ~ "Car - Left Side", 
                                      "汽車 - 右前車頭(身)" ~ "Car - Front Right",
                                      "汽車 - 右後車尾(身)" ~ "Car - Rear Right",
                                      "汽車 - 左後車尾(身)" ~ "Car - Rear Left",
                                      "汽車 - 左前車頭(身)" ~ "Car - Front Left", 
                                      "汽車 - 車頂" ~ "Car - Roof",
                                      "汽車 - 車底" ~ "Car - Undercarriage",
                                      "機車與自行車 - 前車頭" ~ "Motorbike / Bicycle - Front",
                                      "機車與自行車 - 右側車身" ~ "Motorbike / Bicycle - Right Side",
                                      "機車與自行車 - 後車尾" ~ "Motorbike / Bicycle - Rear", 
                                      "機車與自行車 - 左側車身" ~ "Motorbike / Bicycle - Left Side",
                                      "其他 - 不明" ~ "Other - Unknown",
                                      "其他 - 無撞擊" ~ "Other - No Impact",
                                      "其他 - 非汽、機及自行車" ~ "Other - Not Car, Motorbike, or Bicycle"
    ),
    
    
    main_cause_code = case_match(肇因碼_主要,
                                 # Driver-related
                                 "駕駛者 - 違規超車" ~ "Driver - Illegal Overtaking",
                                 "駕駛者 - 爭(搶)道行駛" ~ "Driver - Lane Competition",
                                 "駕駛者 - 危險駕駛" ~ "Driver - Dangerous Driving",
                                 "駕駛者 - 逆向行駛" ~ "Driver - Wrong-way Driving",
                                 "駕駛者 - 超速駕駛" ~ "Driver - Speeding",
                                 "駕駛者 - 未依規定減速" ~ "Driver - Failure to Decelerate",
                                 "駕駛者 - 未保持行車安全距離" ~ "Driver - Unsafe Following Distance",
                                 "駕駛者 - 未保持行車安全間隔" ~ "Driver - Unsafe Lateral Distance",
                                 "駕駛者 - 未遵守依法令授權交通指揮人員之指揮" ~ "Driver - Disregard Traffic Officer",
                                 "駕駛者 - 車輛未依規定暫停讓行人先行" ~ "Driver - Failed to Yield to Pedestrians",
                                 "駕駛者 - 有號誌路口，轉彎車未讓直行車先行" ~ "Driver - Turn Did Not Yield at Signal",
                                 "駕駛者 - 無號誌路口，支線道未讓幹線道先行" ~ "Driver - Minor Road Did Not Yield",
                                 "駕駛者 - 無號誌路口，少線道未讓多線道先行" ~ "Driver - Fewer Lanes Did Not Yield",
                                 "駕駛者 - 無號誌路口，轉彎車未讓直行車先行" ~ "Driver - Turn Did Not Yield at Unsignalized Intersection",
                                 "駕駛者 - 無號誌路口，左方車未讓右方車先行" ~ "Driver - Left Vehicle Did Not Yield Right Vehicle",
                                 "駕駛者 - 山路會車，靠山壁車未讓外緣車先行" ~ "Driver - Mountain Road Passing, Inner Lane Did Not Yield",
                                 "駕駛者 - 峻狹坡路會車，下坡車未讓上坡車先行" ~ "Driver - Narrow Slope, Downhill Did Not Yield",
                                 "駕駛者 - 行經圓環未依規定讓車" ~ "Driver - Did Not Yield in Roundabout",
                                 "駕駛者 - 未依規定避讓消防、救護、警備、工程救險車、毒性化學物質災害事故應變車等執行緊急任務車" ~ "Driver - Did Not Yield to Emergency Vehicles",
                                 "駕駛者 - 其他未依規定讓車" ~ "Driver - Other Failure to Yield",
                                 "駕駛者 - 闖紅燈直行" ~ "Driver - Ran Red Light Straight",
                                 "駕駛者 - 闖紅燈右轉" ~ "Driver - Ran Red Light Right Turn",
                                 "駕駛者 - 闖紅燈左轉（或迴轉）" ~ "Driver - Ran Red Light Left Turn/UTurn",
                                 "駕駛者 - 違反閃光號誌" ~ "Driver - Violated Flashing Signal",
                                 "駕駛者 - 違反其他號誌" ~ "Driver - Violated Other Signal",
                                 "駕駛者 - 違反遵行方向標誌（線）" ~ "Driver - Violated Directional Signage",
                                 "駕駛者 - 違反車輛專用標誌（線）" ~ "Driver - Violated Vehicle-Specific Signage",
                                 "駕駛者 - 違反行人專用標誌（線）" ~ "Driver - Violated Pedestrian Signage",
                                 "駕駛者 - 違反禁止進入標誌" ~ "Driver - Violated No Entry Sign",
                                 "駕駛者 - 違反禁止各種車輛進入標誌" ~ "Driver - Violated Vehicle Ban Sign",
                                 "駕駛者 - 違反禁止會車標誌" ~ "Driver - Violated No Passing Sign",
                                 "駕駛者 - 違反禁止迴轉或迴車標誌" ~ "Driver - Violated No U-Turn Sign",
                                 "駕駛者 - 違反車輛改道標誌" ~ "Driver - Violated Detour Sign",
                                 "駕駛者 - 違反禁止超車標誌（線）" ~ "Driver - Violated No Overtaking Sign",
                                 "駕駛者 - 違反禁止變換車道標線" ~ "Driver - Violated Lane Change Prohibition",
                                 "駕駛者 - 違反二段式左（右）轉標誌（線）" ~ "Driver - Violated Two-Stage Turn Sign",
                                 "駕駛者 - 違反禁行車種標誌（字）" ~ "Driver - Violated Vehicle Type Prohibition",
                                 "駕駛者 - 違反禁止左轉、右轉標誌" ~ "Driver - Violated No Turn Sign",
                                 "駕駛者 - 違反其他標誌（線）禁制" ~ "Driver - Violated Other Signage",
                                 "駕駛者 - 變換車道不當" ~ "Driver - Improper Lane Change",
                                 "駕駛者 - 未靠右行駛" ~ "Driver - Did Not Keep Right",
                                 "駕駛者 - 方向不定（不包括危險駕車）" ~ "Driver - Unsteady Direction",
                                 "駕駛者 - 閃避不當（慎）" ~ "Driver - Improper Evasion",
                                 "駕駛者 - 多車道迴轉，未先駛入內側車道" ~ "Driver - Multi-Lane U-Turn Improper",
                                 "駕駛者 - 迴轉未依規定" ~ "Driver - U-Turn Not According to Rules",
                                 "駕駛者 - 橫越道路不慎" ~ "Driver - Careless Crossing",
                                 "駕駛者 - 右轉彎未依規定" ~ "Driver - Improper Right Turn",
                                 "駕駛者 - 左轉彎未依規定" ~ "Driver - Improper Left Turn",
                                 "駕駛者 - 倒車未依規定" ~ "Driver - Improper Reverse",
                                 "駕駛者 - 停車操作時未注意安全" ~ "Driver - Unsafe While Parking",
                                 "駕駛者 - 起步時未注意安全" ~ "Driver - Unsafe Start",
                                 "駕駛者 - 吸食違禁物駕駛" ~ "Driver - Driving Under Influence of Drugs",
                                 "駕駛者 - 酒醉（後）駕駛" ~ "Driver - Driving Under Alcohol Influence",
                                 "駕駛者 - 患病或服用藥物（疲勞）駕駛" ~ "Driver - Ill or Fatigued Driving",
                                 "駕駛者 - 打瞌睡或疲勞駕駛（包括連續駕車8小時）" ~ "Driver - Drowsy / Fatigued Driving",
                                 "駕駛者 - 飲食、抽（點）菸、拿（撿）物品分心駕駛" ~ "Driver - Distracted by Eating, Smoking, Handling Objects",
                                 "駕駛者 - 乘客、車上動（生）物干擾分心駕駛" ~ "Driver - Distracted by Passengers or Animals",
                                 "駕駛者 - 觀看其他事故、活動、道路環境或車外資訊分心駕駛" ~ "Driver - Distracted by External Information",
                                 "駕駛者 - 恍神、緊張、心不在焉分心駕駛" ~ "Driver - Distracted / Absent-minded",
                                 "駕駛者 - 使用車輛自動駕駛或先進駕駛輔助系統設備（裝置）不符規定" ~ "Driver - Misuse of ADAS/Autonomous System",
                                 "駕駛者 - 操作、觀看行車輔助或娛樂性顯示設備" ~ "Driver - Using Driving/Entertainment Displays",
                                 "駕駛者 - 使用手持行動電話" ~ "Driver - Using Handheld Phone",
                                 "駕駛者 - 搶（闖）越平交道" ~ "Driver - Illegally Crossing Railway Crossing",
                                 "駕駛者 - 未保持平交道淨空" ~ "Driver - Did Not Keep Crossing Clear",
                                 
                                 # Lights
                                 "燈光 - 未依規定使用燈光" ~ "Lights - Improper Use",
                                 "燈光 - 暗處停車無燈光、標識" ~ "Lights - Parked Without Lights in Dark",
                                 "燈光 - 夜間行駛無燈光設備" ~ "Lights - No Lighting at Night",
                                 
                                 # Load / Cargo
                                 "裝載 - 裝載貨物不穩妥" ~ "Load - Unstable Cargo",
                                 "裝載 - 載運貨物超重" ~ "Load - Overweight",
                                 "裝載 - 超載人員" ~ "Load - Excess Passengers",
                                 "裝載 - 載運貨物超長、寬、高" ~ "Load - Oversized Cargo",
                                 "裝載 - 裝卸貨物不當" ~ "Load - Improper Loading/Unloading",
                                 "裝載 - 裝載未盡安全措施" ~ "Load - Safety Measures Not Taken",
                                 "裝載 - 未待乘客安全上下而開車" ~ "Load - Departed Before Passenger Secured",
                                 "裝載 - 其他裝載不當" ~ "Load - Other Improper Loading",
                                 
                                 # Others / Non-driver
                                 "其他 - 開啟或關閉車門不當" ~ "Other - Improper Door Operation",
                                 "其他 - 違規（臨時）停車" ~ "Other - Illegal (Temporary) Parking",
                                 "其他 - 車輛未停妥滑動致生事故" ~ "Other - Vehicle Slid After Parking",
                                 "其他 - 車輛拋錨未採安全措施" ~ "Other - Vehicle Broke Down, No Safety Measures",
                                 "其他 - 發生事故後未採取安全措施" ~ "Other - No Safety Measures After Accident",
                                 "其他 - 被車輛輾壓之不明物體彈飛" ~ "Other - Unknown Object Hit By Vehicle",
                                 "其他 - 車輛或機械操作不當（慎）" ~ "Other - Improper Vehicle / Machine Operation",
                                 "其他 - 因光線、視線遮蔽致生事故" ~ "Other - Accident Due to Obstructed Vision",
                                 "其他 - 其他不當駕車行為" ~ "Other - Other Improper Driving",
                                 "其他 - 相關跡證不足且無具體影像畫面，當事人各執一詞，經分析後無法釐清肇事原因" ~ "Other - Insufficient Evidence / Cannot Determine Cause",
                                 "其他 - 肇事逃逸未查獲，無法查明肇因" ~ "Other - Hit & Run Unknown Cause",
                                 
                                 # Not Yet Determined
                                 "無（車輛駕駛者因素） - 尚未發現肇事因素" ~ "None (Driver Factor) - Cause Not Yet Found",
                                 
                                 # Mechanical
                                 "機件 - 煞車失靈或故障" ~ "Mechanical - Brake Failure",
                                 "機件 - 方向操縱系統故障" ~ "Mechanical - Steering System Failure",
                                 "機件 - 車輪脫落或輪胎爆裂" ~ "Mechanical - Wheel/Tire Failure",
                                 "機件 - 車輛零件脫落" ~ "Mechanical - Vehicle Part Detached",
                                 "機件 - 燈光系統故障" ~ "Mechanical - Lighting System Failure",
                                 "機件 - 車輛附屬機具未盡安全措施" ~ "Mechanical - Auxiliary Equipment Unsafe",
                                 "機件 - 其他機件失靈或故障" ~ "Mechanical - Other Malfunction",
                                 
                                 # Non-driver
                                 "非駕駛者 - 未依標誌或標線穿越道路" ~ "Non-driver - Did Not Follow Road Signs/Markings",
                                 "非駕駛者 - 未依號誌或手勢指揮（示）穿越道路" ~ "Non-driver - Did Not Follow Signals/Hand Gestures",
                                 "非駕駛者 - 未依規定行走地下道、天橋穿越道路" ~ "Non-driver - Did Not Use Pedestrian Overpass/Underpass",
                                 "非駕駛者 - 穿越道路未注意左右來車" ~ "Non-driver - Careless Road Crossing",
                                 "非駕駛者 - 在道路上嬉戲或奔走不定" ~ "Non-driver - Playing/Running on Road",
                                 "非駕駛者 - 搶（闖）越平交道" ~ "Non-driver - Illegally Crossing Railway",
                                 "非駕駛者 - 事故發生時當事者逕自離開現場" ~ "Non-driver - Left Scene After Accident",
                                 "非駕駛者 - 開啟或關閉車門不當" ~ "Non-driver - Improper Door Operation",
                                 "非駕駛者 - 頭手伸出車外" ~ "Non-driver - Head/Hands Outside Vehicle",
                                 "非駕駛者 - 乘坐不當（慎）" ~ "Non-driver - Improper Riding",
                                 "非駕駛者 - 未待車輛停妥而上下車" ~ "Non-driver - Enter/Exit Before Vehicle Stops",
                                 "非駕駛者 - 上下車輛時未注意安全" ~ "Non-driver - Unsafe Enter/Exit",
                                 "非駕駛者 - 在道路上工作未設適當標識" ~ "Non-driver - Working on Road Without Signage",
                                 "非駕駛者 - 指揮不當(包括未依法令授權)" ~ "Non-driver - Improper Traffic Control",
                                 "非駕駛者 - 其他引起事故之疏失或行為" ~ "Non-driver - Other Unsafe Actions",
                                 
                                 # Traffic Control / Facilities
                                 "交通管制(設施) - 平交道看守疏失或未放柵欄" ~ "Traffic Control - Crossing Guard Negligence",
                                 "交通管制(設施) - 路況危險無安全（警告）設施" ~ "Traffic Control - Unsafe Road Conditions",
                                 "交通管制(設施) - 施工安全防護措施未依規定或未盡完善（備）" ~ "Traffic Control - Construction Safety Inadequate",
                                 "交通管制(設施) - 交通管制設施失靈或損毀" ~ "Traffic Control - Control Device Malfunction",
                                 "交通管制(設施) - 其他交通管制不當" ~ "Traffic Control - Other Improper Control",
                                 
                                 # Objects / Animals / Environment
                                 "無（物或動物） - 道路設施（備）、植栽或其他裝置，倒塌或掉（斷）落" ~ "None (Object/Animal) - Road Facility Fell",
                                 "無（物或動物） - 物品（件）滾（滑行）或飛（掉）落" ~ "None (Object/Animal) - Objects Rolled/Fell",
                                 "無（物或動物） - 強風、暴雨、濃霧（煙）" ~ "None (Object/Animal) - Weather Hazard",
                                 "無（物或動物） - 動物竄出" ~ "None (Object/Animal) - Animal Ran Out",
                                 "無（物或動物） - 尚未發現肇事因素" ~ "None (Object/Animal) - Cause Not Yet Found"
    ),
    
    
    
    secondary_cause_code = case_match(肇因碼_個別,
                                 # Driver-related
                                 "駕駛者 - 違規超車" ~ "Driver - Illegal Overtaking",
                                 "駕駛者 - 爭(搶)道行駛" ~ "Driver - Lane Competition",
                                 "駕駛者 - 危險駕駛" ~ "Driver - Dangerous Driving",
                                 "駕駛者 - 逆向行駛" ~ "Driver - Wrong-way Driving",
                                 "駕駛者 - 超速駕駛" ~ "Driver - Speeding",
                                 "駕駛者 - 未依規定減速" ~ "Driver - Failure to Decelerate",
                                 "駕駛者 - 未保持行車安全距離" ~ "Driver - Unsafe Following Distance",
                                 "駕駛者 - 未保持行車安全間隔" ~ "Driver - Unsafe Lateral Distance",
                                 "駕駛者 - 未遵守依法令授權交通指揮人員之指揮" ~ "Driver - Disregard Traffic Officer",
                                 "駕駛者 - 車輛未依規定暫停讓行人先行" ~ "Driver - Failed to Yield to Pedestrians",
                                 "駕駛者 - 有號誌路口，轉彎車未讓直行車先行" ~ "Driver - Turn Did Not Yield at Signal",
                                 "駕駛者 - 無號誌路口，支線道未讓幹線道先行" ~ "Driver - Minor Road Did Not Yield",
                                 "駕駛者 - 無號誌路口，少線道未讓多線道先行" ~ "Driver - Fewer Lanes Did Not Yield",
                                 "駕駛者 - 無號誌路口，轉彎車未讓直行車先行" ~ "Driver - Turn Did Not Yield at Unsignalized Intersection",
                                 "駕駛者 - 無號誌路口，左方車未讓右方車先行" ~ "Driver - Left Vehicle Did Not Yield Right Vehicle",
                                 "駕駛者 - 山路會車，靠山壁車未讓外緣車先行" ~ "Driver - Mountain Road Passing, Inner Lane Did Not Yield",
                                 "駕駛者 - 峻狹坡路會車，下坡車未讓上坡車先行" ~ "Driver - Narrow Slope, Downhill Did Not Yield",
                                 "駕駛者 - 行經圓環未依規定讓車" ~ "Driver - Did Not Yield in Roundabout",
                                 "駕駛者 - 未依規定避讓消防、救護、警備、工程救險車、毒性化學物質災害事故應變車等執行緊急任務車" ~ "Driver - Did Not Yield to Emergency Vehicles",
                                 "駕駛者 - 其他未依規定讓車" ~ "Driver - Other Failure to Yield",
                                 "駕駛者 - 闖紅燈直行" ~ "Driver - Ran Red Light Straight",
                                 "駕駛者 - 闖紅燈右轉" ~ "Driver - Ran Red Light Right Turn",
                                 "駕駛者 - 闖紅燈左轉（或迴轉）" ~ "Driver - Ran Red Light Left Turn/UTurn",
                                 "駕駛者 - 違反閃光號誌" ~ "Driver - Violated Flashing Signal",
                                 "駕駛者 - 違反其他號誌" ~ "Driver - Violated Other Signal",
                                 "駕駛者 - 違反遵行方向標誌（線）" ~ "Driver - Violated Directional Signage",
                                 "駕駛者 - 違反車輛專用標誌（線）" ~ "Driver - Violated Vehicle-Specific Signage",
                                 "駕駛者 - 違反行人專用標誌（線）" ~ "Driver - Violated Pedestrian Signage",
                                 "駕駛者 - 違反禁止進入標誌" ~ "Driver - Violated No Entry Sign",
                                 "駕駛者 - 違反禁止各種車輛進入標誌" ~ "Driver - Violated Vehicle Ban Sign",
                                 "駕駛者 - 違反禁止會車標誌" ~ "Driver - Violated No Passing Sign",
                                 "駕駛者 - 違反禁止迴轉或迴車標誌" ~ "Driver - Violated No U-Turn Sign",
                                 "駕駛者 - 違反車輛改道標誌" ~ "Driver - Violated Detour Sign",
                                 "駕駛者 - 違反禁止超車標誌（線）" ~ "Driver - Violated No Overtaking Sign",
                                 "駕駛者 - 違反禁止變換車道標線" ~ "Driver - Violated Lane Change Prohibition",
                                 "駕駛者 - 違反二段式左（右）轉標誌（線）" ~ "Driver - Violated Two-Stage Turn Sign",
                                 "駕駛者 - 違反禁行車種標誌（字）" ~ "Driver - Violated Vehicle Type Prohibition",
                                 "駕駛者 - 違反禁止左轉、右轉標誌" ~ "Driver - Violated No Turn Sign",
                                 "駕駛者 - 違反其他標誌（線）禁制" ~ "Driver - Violated Other Signage",
                                 "駕駛者 - 變換車道不當" ~ "Driver - Improper Lane Change",
                                 "駕駛者 - 未靠右行駛" ~ "Driver - Did Not Keep Right",
                                 "駕駛者 - 方向不定（不包括危險駕車）" ~ "Driver - Unsteady Direction",
                                 "駕駛者 - 閃避不當（慎）" ~ "Driver - Improper Evasion",
                                 "駕駛者 - 多車道迴轉，未先駛入內側車道" ~ "Driver - Multi-Lane U-Turn Improper",
                                 "駕駛者 - 迴轉未依規定" ~ "Driver - U-Turn Not According to Rules",
                                 "駕駛者 - 橫越道路不慎" ~ "Driver - Careless Crossing",
                                 "駕駛者 - 右轉彎未依規定" ~ "Driver - Improper Right Turn",
                                 "駕駛者 - 左轉彎未依規定" ~ "Driver - Improper Left Turn",
                                 "駕駛者 - 倒車未依規定" ~ "Driver - Improper Reverse",
                                 "駕駛者 - 停車操作時未注意安全" ~ "Driver - Unsafe While Parking",
                                 "駕駛者 - 起步時未注意安全" ~ "Driver - Unsafe Start",
                                 "駕駛者 - 吸食違禁物駕駛" ~ "Driver - Driving Under Influence of Drugs",
                                 "駕駛者 - 酒醉（後）駕駛" ~ "Driver - Driving Under Alcohol Influence",
                                 "駕駛者 - 患病或服用藥物（疲勞）駕駛" ~ "Driver - Ill or Fatigued Driving",
                                 "駕駛者 - 打瞌睡或疲勞駕駛（包括連續駕車8小時）" ~ "Driver - Drowsy / Fatigued Driving",
                                 "駕駛者 - 飲食、抽（點）菸、拿（撿）物品分心駕駛" ~ "Driver - Distracted by Eating, Smoking, Handling Objects",
                                 "駕駛者 - 乘客、車上動（生）物干擾分心駕駛" ~ "Driver - Distracted by Passengers or Animals",
                                 "駕駛者 - 觀看其他事故、活動、道路環境或車外資訊分心駕駛" ~ "Driver - Distracted by External Information",
                                 "駕駛者 - 恍神、緊張、心不在焉分心駕駛" ~ "Driver - Distracted / Absent-minded",
                                 "駕駛者 - 使用車輛自動駕駛或先進駕駛輔助系統設備（裝置）不符規定" ~ "Driver - Misuse of ADAS/Autonomous System",
                                 "駕駛者 - 操作、觀看行車輔助或娛樂性顯示設備" ~ "Driver - Using Driving/Entertainment Displays",
                                 "駕駛者 - 使用手持行動電話" ~ "Driver - Using Handheld Phone",
                                 "駕駛者 - 搶（闖）越平交道" ~ "Driver - Illegally Crossing Railway Crossing",
                                 "駕駛者 - 未保持平交道淨空" ~ "Driver - Did Not Keep Crossing Clear",
                                 
                                 # Lights
                                 "燈光 - 未依規定使用燈光" ~ "Lights - Improper Use",
                                 "燈光 - 暗處停車無燈光、標識" ~ "Lights - Parked Without Lights in Dark",
                                 "燈光 - 夜間行駛無燈光設備" ~ "Lights - No Lighting at Night",
                                 
                                 # Load / Cargo
                                 "裝載 - 裝載貨物不穩妥" ~ "Load - Unstable Cargo",
                                 "裝載 - 載運貨物超重" ~ "Load - Overweight",
                                 "裝載 - 超載人員" ~ "Load - Excess Passengers",
                                 "裝載 - 載運貨物超長、寬、高" ~ "Load - Oversized Cargo",
                                 "裝載 - 裝卸貨物不當" ~ "Load - Improper Loading/Unloading",
                                 "裝載 - 裝載未盡安全措施" ~ "Load - Safety Measures Not Taken",
                                 "裝載 - 未待乘客安全上下而開車" ~ "Load - Departed Before Passenger Secured",
                                 "裝載 - 其他裝載不當" ~ "Load - Other Improper Loading",
                                 
                                 # Others / Non-driver
                                 "其他 - 開啟或關閉車門不當" ~ "Other - Improper Door Operation",
                                 "其他 - 違規（臨時）停車" ~ "Other - Illegal (Temporary) Parking",
                                 "其他 - 車輛未停妥滑動致生事故" ~ "Other - Vehicle Slid After Parking",
                                 "其他 - 車輛拋錨未採安全措施" ~ "Other - Vehicle Broke Down, No Safety Measures",
                                 "其他 - 發生事故後未採取安全措施" ~ "Other - No Safety Measures After Accident",
                                 "其他 - 被車輛輾壓之不明物體彈飛" ~ "Other - Unknown Object Hit By Vehicle",
                                 "其他 - 車輛或機械操作不當（慎）" ~ "Other - Improper Vehicle / Machine Operation",
                                 "其他 - 因光線、視線遮蔽致生事故" ~ "Other - Accident Due to Obstructed Vision",
                                 "其他 - 其他不當駕車行為" ~ "Other - Other Improper Driving",
                                 "其他 - 相關跡證不足且無具體影像畫面，當事人各執一詞，經分析後無法釐清肇事原因" ~ "Other - Insufficient Evidence / Cannot Determine Cause",
                                 "其他 - 肇事逃逸未查獲，無法查明肇因" ~ "Other - Hit & Run Unknown Cause",
                                 
                                 # Not Yet Determined
                                 "無（車輛駕駛者因素） - 尚未發現肇事因素" ~ "None (Driver Factor) - Cause Not Yet Found",
                                 
                                 # Mechanical
                                 "機件 - 煞車失靈或故障" ~ "Mechanical - Brake Failure",
                                 "機件 - 方向操縱系統故障" ~ "Mechanical - Steering System Failure",
                                 "機件 - 車輪脫落或輪胎爆裂" ~ "Mechanical - Wheel/Tire Failure",
                                 "機件 - 車輛零件脫落" ~ "Mechanical - Vehicle Part Detached",
                                 "機件 - 燈光系統故障" ~ "Mechanical - Lighting System Failure",
                                 "機件 - 車輛附屬機具未盡安全措施" ~ "Mechanical - Auxiliary Equipment Unsafe",
                                 "機件 - 其他機件失靈或故障" ~ "Mechanical - Other Malfunction",
                                 
                                 # Non-driver
                                 "非駕駛者 - 未依標誌或標線穿越道路" ~ "Non-driver - Did Not Follow Road Signs/Markings",
                                 "非駕駛者 - 未依號誌或手勢指揮（示）穿越道路" ~ "Non-driver - Did Not Follow Signals/Hand Gestures",
                                 "非駕駛者 - 未依規定行走地下道、天橋穿越道路" ~ "Non-driver - Did Not Use Pedestrian Overpass/Underpass",
                                 "非駕駛者 - 穿越道路未注意左右來車" ~ "Non-driver - Careless Road Crossing",
                                 "非駕駛者 - 在道路上嬉戲或奔走不定" ~ "Non-driver - Playing/Running on Road",
                                 "非駕駛者 - 搶（闖）越平交道" ~ "Non-driver - Illegally Crossing Railway",
                                 "非駕駛者 - 事故發生時當事者逕自離開現場" ~ "Non-driver - Left Scene After Accident",
                                 "非駕駛者 - 開啟或關閉車門不當" ~ "Non-driver - Improper Door Operation",
                                 "非駕駛者 - 頭手伸出車外" ~ "Non-driver - Head/Hands Outside Vehicle",
                                 "非駕駛者 - 乘坐不當（慎）" ~ "Non-driver - Improper Riding",
                                 "非駕駛者 - 未待車輛停妥而上下車" ~ "Non-driver - Enter/Exit Before Vehicle Stops",
                                 "非駕駛者 - 上下車輛時未注意安全" ~ "Non-driver - Unsafe Enter/Exit",
                                 "非駕駛者 - 在道路上工作未設適當標識" ~ "Non-driver - Working on Road Without Signage",
                                 "非駕駛者 - 指揮不當(包括未依法令授權)" ~ "Non-driver - Improper Traffic Control",
                                 "非駕駛者 - 其他引起事故之疏失或行為" ~ "Non-driver - Other Unsafe Actions",
                                 
                                 # Traffic Control / Facilities
                                 "交通管制(設施) - 平交道看守疏失或未放柵欄" ~ "Traffic Control - Crossing Guard Negligence",
                                 "交通管制(設施) - 路況危險無安全（警告）設施" ~ "Traffic Control - Unsafe Road Conditions",
                                 "交通管制(設施) - 施工安全防護措施未依規定或未盡完善（備）" ~ "Traffic Control - Construction Safety Inadequate",
                                 "交通管制(設施) - 交通管制設施失靈或損毀" ~ "Traffic Control - Control Device Malfunction",
                                 "交通管制(設施) - 其他交通管制不當" ~ "Traffic Control - Other Improper Control",
                                 
                                 # Objects / Animals / Environment
                                 "無（物或動物） - 道路設施（備）、植栽或其他裝置，倒塌或掉（斷）落" ~ "None (Object/Animal) - Road Facility Fell",
                                 "無（物或動物） - 物品（件）滾（滑行）或飛（掉）落" ~ "None (Object/Animal) - Objects Rolled/Fell",
                                 "無（物或動物） - 強風、暴雨、濃霧（煙）" ~ "None (Object/Animal) - Weather Hazard",
                                 "無（物或動物） - 動物竄出" ~ "None (Object/Animal) - Animal Ran Out",
                                 "無（物或動物） - 尚未發現肇事因素" ~ "None (Object/Animal) - Cause Not Yet Found"
    ),
    
    personal_hit_and_run = case_match(個人肇逃否,
                       "否" ~ "No",
                       "是" ~ "Yes"),
    
    occupation = case_match(職業,
                    "民意代表、行政主管、企業主管及經理人員" ~ "Elected Officials, Administrative Executives, Business Executives/Managers",
                    "專業人員" ~ "Professionals",
                    "技術員及助理人員" ~ "Technicians and Assistants",
                    "事務工作者" ~ "Clerical Workers",
                    "服務工作者" ~ "Service Workers",
                    "售貨員" ~ "Salespersons",
                    "農林漁牧工作者" ~ "Agriculture, Forestry, Fishery, and Livestock Workers",
                    "保安工作者(不含警察人員)" ~ "Security Workers (Excluding Police)",
                    "技術工" ~ "Skilled Workers",
                    "汽車、火車駕駛員及船員" ~ "Car/Train Drivers and Crew",
                    "機械設備操作工及組裝工" ~ "Machine Operators and Assemblers",
                    "非技術工及體力工" ~ "Unskilled and Manual Laborers",
                    "未就學兒童" ~ "Preschool Children",
                    "小學生（1-6 年級）" ~ "Elementary Students (Grades 1-6)",
                    "國中生（7-9 年級）" ~ "Junior High Students (Grades 7-9)",
                    "高中（職）生" ~ "High School / Vocational Students",
                    "專科生" ~ "College / Technical School Students",
                    "大學(研究)生" ~ "University / Graduate Students",
                    "家庭主婦(夫)" ~ "Homemakers",
                    "無業者" ~ "Unemployed",
                    "其他" ~ "Other",
                    "不明" ~ "Unknown",
                    "警察人員" ~ "Police Officers",
                    "6 歲以下嬰幼童" ~ "Children Under 6 Years Old",
                    "大學生（專科、院校、研究所）" ~ "College Students (Technical / University / Graduate)",
                    "勞工人員" ~ "Laborers"),
    
    trip_purpose = case_match(旅次目的, 
                      "上、下班" ~ "Commuting to/from Work",
                      "上、下學" ~ "Commuting to/from School",
                      "業務聯繫" ~ "Business Trip / Work Contact",
                      "運輸" ~ "Transport / Delivery",
                      "社交活動" ~ "Social Activities",
                      "觀光旅遊" ~ "Sightseeing / Tourism",
                      "購物" ~ "Shopping",
                      "其他" ~ "Other",
                      "不明" ~ "Unknown")
          
          
          
          
          
          ) |>
  
  # return same columns as in Chinese
  
  select(incident_date = 發生日期,
         incident_time = 發生時間,
         incident_datetime = 發生日期時間,
         incident_year = 發生年度,
         incident_month = 發生月,
         incident_day = 發生日,
         incident_hour = 發生時_Hours,
         incident_minute =發生分,
         handling_type_code = 處理別_編號,
         district = 區序,
         incident_location = 肇事地點,
         number_of_dead = 死亡人數,
         number_of_injured = 受傷人數,
         當事人序號,
         vehicle_type,
         sex,
         age = 年齡,
         
         injury_severity,
         weather,
         speed_limit = 速限_速度限制,
         road_type,
         accident_location,
         
         x_coord = 座標_X,
         y_coord = 座標_Y,
         
         number_of_deaths_2_30_days_later = 後_2_30日死亡人數,
         
         lighting,
         road_lighting,
         road_category,
         road_surface_material,
         road_surface_condition,
         road_defect,
         
         
         road_obstacle_type,
         road_obstacle_visibility,
         signal_type,
         signal_operation,
         lane_division_direction,
         lane_division_fast_or_normal,
         lane_division_fast_slow,
         lane_division_edge_line,
         accident_type_and_pattern,
         main_injury_location,
         protective_device,
         helmet,
         mobile_phone_use,
         vehicle_purpose,
         participant_action_status,
         driver_license_status,
         driver_license_type,
         alcohol_status,
         vehicle_impact_part1,
         vehicle_impact_part2,
         main_cause_code,
         secondary_cause_code, 
         personal_hit_and_run,
         occupation, 
         trip_purpose, 
         
         accident_id)
